<?php
interface Human{
    public function getName();
    public function setName($name);
}

abstract class miltery{

    private $rank;

    public function __construct($rank)
    {
        $this->rank = $rank;
    }

    /**
     * @param mixed $rank
     */
    public function setRank($rank)
    {
        $this->rank = $rank;
    }

    /**
     * @return mixed
     */
    public function getRank()
    {
        return $this->rank;
    }
}

class soilder extends miltery implements Human{
    public $name;
    public function __construct($name,$rank)
    {
        $this->name=$name;
        parent::__construct($rank);
    }

    /**
     * @param $name
     */
    public function setName($name)
    {
        $this->name=$name;
    }

    public function getName()
    {
        echo "My name is:".$this->name;
    }
    public  function getRank()
    {
        echo parent::getRank(); // TODO: Change the autogenerated stub
    }
     public  function getRankret()
    {
        return parent::getRank(); // TODO: Change the autogenerated stub
    }

    public function alldata(){
        echo "my name is :".$this->name."and rank is:".$this->getRankret();

    }
}

$obj = new soilder("test1",13);
$obj->getRank();
$obj->getName();

$obj->alldata();

echo "<br>";

$obj->setName("test2");
$obj->setRank(28);

$obj->getRank();
$obj->getName();
$obj->alldata();
